### ISSUE TITLE
Getting some extensions working

### ISSUE THREAD

**Issue by sibwaze** [FoxRefire/ChromeXPIPorter#2]
Hello
Thank you for your hard work. This extension is something i've been looking for a long time.
But extension for my job purposes is not working properly. How can i help you or what can i do to make this extension work?
It installs successfully, but when it tries to connect to server (that's it functionality), it can't authenticate (asks me to login in corporate website it connects to)
So seems like maybe it doesn't have a permission or something to connect to the internet. Maybe this helps. I can help you with more info if you need it. Thanks in advance!

**Comment by sibwaze** [comment]
If this can help, there is screenshot from devtools with an error when i try to use functional of my extension
![изображение](https://github.com/user-attachments/assets/5fae4404-d6e7-4a1b-97ce-2eeb2f65105c)

**Comment by FoxRefire** [comment]
Hello.
Thank you for your interest in my OSS project.
Navigate to `about:debugging#/runtime/this-firefox`, Inspect extension and paste the console log.
And if possible, upload your CRX or paste the Chrome Web Store link here.

**Comment by sibwaze** [comment]
Hello, maybe i do something wrong, but here it is. I clicked "inspect extension", then tried to use it as usually, and copied the log from inspect console
![изображение](https://github.com/user-attachments/assets/dcfc2470-ac85-4331-9517-34f75447b060)
![изображение](https://github.com/user-attachments/assets/7bdd33ff-8308-4f5d-926d-606ae8e1d5d7)
![изображение](https://github.com/user-attachments/assets/60bf3751-142d-4290-968e-838d5b66971d)

**Comment by FoxRefire** [comment]
The allowed redirect URLs for OAuth must be set on the authentication server side and cannot be resolved on the extension side alone.
If you set `browser_specific_settings.gecko.id` in `manifest.json`, the [`chrome.identity.getRedirectURL()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity/getRedirectURL) API will gives fixed value URL based on this id.
This must be set as the allowed redirect URL to the authentication server.

Porting Chrome extensions to Firefox is very easy in most cases.

```diff
{
    <OMITTED>,
    "background": {
-       "service_worker": "background.js"
+       "scripts": ["background.js"]
    },
    <OMITTED>,
+   "browser_specific_settings": {
+       "gecko": {
+           "id": "AnyID@AnyID"
+       }
+   }
}
```
After making the above changes to `manifest.json`, all that remains is to fix the problems that occur individually.

Then do the following:
![Screenshot_20240924_190950](https://github.com/user-attachments/assets/b70b0ef0-07b3-4c65-bda2-3b14430a020a)

**Comment by sibwaze** [comment]
Thank you! I will report the developer to make those commits.
