### ISSUE TITLE
Facing issue in Zen browser

### ISSUE THREAD

**Issue by RABINGG** [FoxRefire/ChromeXPIPorter#4]
![image](https://github.com/user-attachments/assets/6450c087-7324-4b82-ac64-bb992282ff55)
Facing the above issue in zen browser. The about config key is also set to false.

**Comment by FoxRefire** [comment]
Works on my side.
If this happens only with some extensions, but not all, write down a CWS link.

**Comment by RABINGG** [comment]
Even the perplexity - AI Companion from Readme doesn't works for me. Same error happens

**Comment by FoxRefire** [comment]
To help us investigating the cause of the issue, I've added a debugging feature in new version.
Open the console and follow the instructions to download the generated XPI, and attach it here.

![Screenshot_20241008_115117](https://github.com/user-attachments/assets/fc626127-167c-4dfb-9610-0ddfe2c38c93)

**Comment by RABINGG** [comment]
Seems to be chrome webstore opened in container that caused the issue
