### ISSUE TITLE
Unable to install Kleo

### ISSUE THREAD

**Issue by Blendertom** [FoxRefire/ChromeXPIPorter#5]
1. Thank you for this - it's been a lifesaver for me.
2. I'm unable to install [Kleo](https://chromewebstore.google.com/detail/kleo/jdedmecbcembcmlddbchlmmoglcldghe) I get an error: This add-on could not be installed because it appears to be corrupt.

**Info**
Browser: Zen Browser 1.0.1-a.7 (64-bit)
OS: macOS Sequoia 15.1

**Comment by FoxRefire** [comment]
May fixed in new version
